import os

from pydantic import BaseModel, Field

from .agent import BaseAgent
from .prompts.storyboarder import STORYBOARDER_PROMPT


class StoryboarderOutput(BaseModel):
    storyboard: str = Field(description="Detailed visual instructions for the animator.")
    animation_instruction: str = Field(description="The instruction to give to the Animator for the animation of this scene")

class Storyboarder(BaseAgent):
    def __init__(self, client):
        super().__init__(
            llm_client=client,
            model=os.getenv("STORYBOARDER_LLM", ""),
            system_prompt=STORYBOARDER_PROMPT,
            agent_name="Storyboarder",
            output_schema=StoryboarderOutput
        )

if __name__ == "__main__":
    import json

    from dotenv import load_dotenv
    from groq import Groq
    load_dotenv()
    
    from visual_explainer.state import AgentState, merge_scenes

    from .planner import Planner, PlannerOutput
    
    client = Groq()

    planner = Planner(client)
    storyboarder = Storyboarder(client)

    planner_output: PlannerOutput = planner.invoke([
        {"role": "user", "content": "Explain the concept of 'Pythagoras theorem'"}
    ])
    print("Planner output generated, handing over to the storyboarders")

    agent_state = AgentState(thread_id="test-thread", topic="Pythagoras theorem", scenes=planner_output.scenes)

    # Spin up different storyboarder instances for each scene
    for scene in agent_state.scenes:
        print(f"Storyboarding for scene {scene.id}...")
        scene_input = [
            {"role": "user", "content": f"Storyboard this scene generated by the planner: {json.dumps(scene.model_dump())}"}
        ]
        storyboarder_output: StoryboarderOutput = storyboarder.invoke(scene_input)

        updated_scene = scene.model_copy(update={
            "storyboard": storyboarder_output.storyboard,
            "animation_instructions": storyboarder_output.animation_instruction
        })
        
        # Use the reducer function now to merge the updates
        agent_state.scenes = merge_scenes(agent_state.scenes, [updated_scene])

    # Print the final central output
    print("Final AgentState output:")
    print(json.dumps([scene.model_dump() for scene in agent_state.scenes], indent=4))
