from typing import Annotated, Dict, List, Literal, Optional, TypedDict, Union

from pydantic import BaseModel, Field


class Scene(BaseModel):
    id: int = Field(description="ID of the Scene")
    # Generated by the planner
    scene_plan: str = Field(description="Description or the plan for the scene, a detail about what this scene is about and what topic is being explained here.")
    script: str = Field(description="Script associate to this Scene")
    
    # Generated by the storyboarder
    storyboard: str = Field(default="", description="How exactly this scene would play out in the code")
    animation_instructions: str = Field(default="", description="The instructions to be given to the Animator for generating the code for this scene")

    # Generated by the animator    
    manim_code: str = Field(default="", description="Code associated with this scene")
    # For use with the animator
    # code_error: str = Field(default="")
    
    # Generated using the code given by the animator; format will be "{thread_id}_segment{id}.mp4"
    audio_path: str = Field(default="", description="Path to where the final generated script audio file for this scene is at")
    video_path: str = Field(default="", description="Path to where the final rendered video file of this scene is stored at")


def merge_scenes(old_scenes: List[Scene], new_scenes: List[Scene]) -> List[Scene]:
    merged_scenes_dict = {scene.id: scene for scene in old_scenes}

    for new_scene in new_scenes:
        # If the new scene is not already existing, just add it to the final output
        if new_scene.id not in merged_scenes_dict.keys():
            merged_scenes_dict[new_scene.id] = new_scene
            continue
        
        old_scene = merged_scenes_dict[new_scene.id]
        
        # Overwrite the video and audio paths that we're expecting will be changed later (all that have a default value)
        old_scene.storyboard = new_scene.storyboard
        old_scene.animation_instructions = new_scene.animation_instructions
        old_scene.manim_code = new_scene.manim_code
        old_scene.video_path = new_scene.video_path
        old_scene.audio_path = new_scene.audio_path
            
    return sorted(merged_scenes_dict.values(), key=lambda x: x.id)

# # For the Director
# class SupervisorAgentState(BaseModel):
#     scenes: List[Scene]
#     next_node = Literal["Planner/Writer", "Storyboarder", "Animator"]

# For the linear workflow
class AgentState(BaseModel):
    thread_id: str = Field(description="ID associated with a particular thread, useful for Langsmith tracing")
    topic: str = Field(default="", description="The topic that the user wants explained to them")
    scenes: Annotated[List[Scene], merge_scenes] = Field(default_factory=list)
    final_video_path: str = Field(default="")
